apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: custom-model
spec:
  predictor:
    containers:
      - name: kserve-container
        image: electricweegie/custom-kserve-endpoint:latest
# apiVersion: serving.kserve.io/v1alpha1
# kind: Service
# metadata:
#   name: custom-kserve-endpoint
# spec:
#   template:
#     spec:
#       containers:
#         - image: electricweegie/custom-kserve-endpoint:latest
#           name: custom-kserve-endpoint
#           ports:
#             - containerPort: 80



# apiVersion: serving.kserve.io/v1beta1
# kind: InferenceService
# metadata:
#   name: custom-kserve-endpoint
# spec:
#   predictor:
#     containers:
#       - name: custom-kserve-endpoint
#         image: electricweegie/custom-kserve-endpoint:latest

